In [22]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

In [23]:
url = 'https://raw.githubusercontent.com/prasertcbs/basic-dataset/master/Advertising.csv'
df = pd.read_csv(url, usecols=[1,2,3,4])
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

## Train test split

In [24]:
df.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [25]:
x = df[['TV','Radio','Newspaper']]
y = df['Sales']

In [26]:
x

        TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [27]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [28]:
x_train, x_test, y_train, y_test = train_test_split(x,y, 
                                                    test_size=0.3,
                                                    random_state=7)

In [29]:
x_train.head()

        TV  Radio  Newspaper
88    88.3   25.5       73.4
58   210.8   49.6       37.7
113  209.6   20.6       10.7
149   44.7   25.8       20.6
36   266.9   43.8        5.0

In [30]:
x_test.head()

        TV  Radio  Newspaper
86    76.3   27.5       16.0
120  141.3   26.8       46.2
22    13.2   15.9       49.6
11   214.7   24.0        4.0
195   38.2    3.7       13.8

In [31]:
y_train.head()

88     12.9
58     23.8
113    15.9
149    10.1
36     25.4
Name: Sales, dtype: float64

In [32]:
y_test.head()

86     12.0
120    15.5
22      5.6
11     17.4
195     7.6
Name: Sales, dtype: float64

## LinearRegression

In [34]:
import sklearn
from sklearn.linear_model import LinearRegression

In [36]:
model = LinearRegression()
model

LinearRegression()

In [37]:
model.fit(x_train,y_train)

LinearRegression()

In [38]:
model.score(x_train,y_train) #R^2

0.8970470429900155

In [39]:
model.intercept_

2.5971913990213054

In [40]:
model.coef_

array([ 4.71259657e-02,  1.90987993e-01, -1.93812266e-05])

In [42]:
model.predict([[300, 50, 70],
               [200, 80, 50],
               [100,90,30]])

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([26.28302406, 27.30045491, 24.4981259 ])

In [43]:
y_hat = model.predict(x_train)
y_hat

array([11.62718541, 22.00361874, 16.40893908,  9.63081303, 23.54028882,
        4.19019633,  6.33372661,  9.16205331, 18.6252243 ,  9.30278314,
       10.02220298, 12.81990978, 16.3270569 , 15.55142217,  8.18788222,
       17.73045095, 24.32738343,  7.98376479, 12.34504657, 23.42048119,
       10.19514611, 17.25432468, 15.17745615, 16.45100472, 16.83421976,
       16.94913148, 14.92719588, 12.08456358, 17.31673623, 20.75868218,
       12.31079013, 14.68033357, 12.00487231,  4.23083643, 11.88897069,
       18.47946596, 17.82345369, 10.62147609, 21.24463139,  3.40353011,
       20.37338186,  9.53396325,  8.95973195, 10.92777341,  8.97930171,
       17.62344551, 20.54153871, 12.60435152, 13.71875285, 17.33050151,
       15.22001133, 20.47732861,  9.86186951, 14.93210984, 13.95134117,
       12.31718956, 16.32085396,  7.16859379, 18.16059791, 20.91470709,
       20.02490033, 18.17883475, 18.49821442, 17.0839661 , 19.35270232,
        4.19833505, 12.50911724, 17.95656145,  6.91422545,  9.90447448,
       10.42119071, 12.78028296, 21.82835372, 23.41577932,  6.56681082,
       14.75847895, 13.47230131, 10.19313548, 13.92501901,  9.78331628,
       21.80450967, 15.30617948, 18.93360192,  9.57166714, 14.29594599,
       13.72711144, 15.006342  , 23.98232793, 13.89828935, 15.32931852,
       10.47352554, 23.06533337, 17.07959565,  6.81947906, 12.30816114,
       10.50213634, 18.4792284 , 21.39075666, 15.56684723,  9.95657766,
       12.1992509 , 14.31888317,  5.78894815, 15.56692342, 21.01396414,
       13.17910445,  9.72701965, 14.34014313,  7.37438608, 13.81839214,
       16.35902724,  8.30717117, 21.19794648,  8.68760535, 14.10308899,
       11.57088514, 21.40418995, 11.73806283, 20.65888105,  7.3593895 ,
       13.84964647,  6.37651554, 20.07072522, 19.03685226, 13.33560266,
       11.2519676 , 21.72370744, 14.80324095, 16.8998523 , 10.16239699,
       16.58323865, 19.32853365, 20.87119297, 19.2534684 , 14.7368069 ,
        9.90278852, 11.93096662, 15.65468781,  7.97214154, 24.98487401])

In [45]:
train = pd.concat([x_train,y_train],axis='columns')
train

        TV  Radio  Newspaper  Sales
88    88.3   25.5       73.4   12.9
58   210.8   49.6       37.7   23.8
113  209.6   20.6       10.7   15.9
149   44.7   25.8       20.6   10.1
36   266.9   43.8        5.0   25.4
..     ...    ...        ...    ...
151  121.0    8.4       48.7   11.6
67   139.3   14.5       10.2   13.4
25   262.9    3.5       19.5   12.0
196   94.2    4.9        8.1    9.7
175  276.9   48.9       41.8   27.0

[140 rows x 4 columns]

In [48]:
dc = pd.concat([train.reset_index(), pd.Series(y_hat, name = 'Predicted')],axis='columns')
dc.head()

   index     TV  Radio  Newspaper  Sales  Predicted
0     88   88.3   25.5       73.4   12.9  11.627185
1     58  210.8   49.6       37.7   23.8  22.003619
2    113  209.6   20.6       10.7   15.9  16.408939
3    149   44.7   25.8       20.6   10.1   9.630813
4     36  266.9   43.8        5.0   25.4  23.540289

In [49]:
y_hat_test = model.predict(x_test)
y_hat

array([11.62718541, 22.00361874, 16.40893908,  9.63081303, 23.54028882,
        4.19019633,  6.33372661,  9.16205331, 18.6252243 ,  9.30278314,
       10.02220298, 12.81990978, 16.3270569 , 15.55142217,  8.18788222,
       17.73045095, 24.32738343,  7.98376479, 12.34504657, 23.42048119,
       10.19514611, 17.25432468, 15.17745615, 16.45100472, 16.83421976,
       16.94913148, 14.92719588, 12.08456358, 17.31673623, 20.75868218,
       12.31079013, 14.68033357, 12.00487231,  4.23083643, 11.88897069,
       18.47946596, 17.82345369, 10.62147609, 21.24463139,  3.40353011,
       20.37338186,  9.53396325,  8.95973195, 10.92777341,  8.97930171,
       17.62344551, 20.54153871, 12.60435152, 13.71875285, 17.33050151,
       15.22001133, 20.47732861,  9.86186951, 14.93210984, 13.95134117,
       12.31718956, 16.32085396,  7.16859379, 18.16059791, 20.91470709,
       20.02490033, 18.17883475, 18.49821442, 17.0839661 , 19.35270232,
        4.19833505, 12.50911724, 17.95656145,  6.91422545,  9.90447448,
       10.42119071, 12.78028296, 21.82835372, 23.41577932,  6.56681082,
       14.75847895, 13.47230131, 10.19313548, 13.92501901,  9.78331628,
       21.80450967, 15.30617948, 18.93360192,  9.57166714, 14.29594599,
       13.72711144, 15.006342  , 23.98232793, 13.89828935, 15.32931852,
       10.47352554, 23.06533337, 17.07959565,  6.81947906, 12.30816114,
       10.50213634, 18.4792284 , 21.39075666, 15.56684723,  9.95657766,
       12.1992509 , 14.31888317,  5.78894815, 15.56692342, 21.01396414,
       13.17910445,  9.72701965, 14.34014313,  7.37438608, 13.81839214,
       16.35902724,  8.30717117, 21.19794648,  8.68760535, 14.10308899,
       11.57088514, 21.40418995, 11.73806283, 20.65888105,  7.3593895 ,
       13.84964647,  6.37651554, 20.07072522, 19.03685226, 13.33560266,
       11.2519676 , 21.72370744, 14.80324095, 16.8998523 , 10.16239699,
       16.58323865, 19.32853365, 20.87119297, 19.2534684 , 14.7368069 ,
        9.90278852, 11.93096662, 15.65468781,  7.97214154, 24.98487401])

In [50]:
test = pd.concat([x_test,y_test],axis='columns')
test.head()

        TV  Radio  Newspaper  Sales
86    76.3   27.5       16.0   12.0
120  141.3   26.8       46.2   15.5
22    13.2   15.9       49.6    5.6
11   214.7   24.0        4.0   17.4
195   38.2    3.7       13.8    7.6

In [52]:
dt = pd.concat([test.reset_index(), pd.Series(y_hat_test, name = 'Predicted')],axis='columns')
dt

    index     TV  Radio  Newspaper  Sales  Predicted
0      86   76.3   27.5       16.0   12.0  11.444762
1     120  141.3   26.8       46.2   15.5  14.373673
2      22   13.2   15.9       49.6    5.6   6.255002
3      11  214.7   24.0        4.0   17.4  17.298771
4     195   38.2    3.7       13.8    7.6   5.103791
5       2   17.2   45.9       69.3    9.3  12.172764
6     121   18.8   21.7       50.4    7.0   7.626622
7      94  107.4   14.0       10.9   11.5  10.332141
8      66   31.5   24.6        2.2    9.5   8.779921
9      63  102.7   29.6        8.4   14.0  13.090110
10    108   13.1    0.4       25.6    5.3   3.290441
11     96  197.6    3.5        5.9   11.7  12.577626
12    138   43.0   25.9       20.5    9.6   9.569800
13     65   69.0    9.3        0.9    9.3   7.625054
14    188  286.0   13.9        3.7   15.9  18.729879
15    155    4.1   11.6        5.7    3.2   5.005758
16     24   62.3   12.6       18.3    9.7   7.939233
17     99  135.2   41.7       45.9   17.2  16.931932
18    153  171.3   39.7       37.7   19.0  18.251362
19     46   89.7    9.9       35.7   10.6   8.714480
20    178  276.7    2.3       23.7   11.8  16.075759
21    139  184.9   43.9        1.7   20.7  19.695122
22    143  104.6    5.7       34.4   10.4   8.614532
23     74  213.4   24.6       13.1   17.0  17.351923
24    186  139.5    2.1       26.6   10.3   9.571823
25    169  284.3   10.6        6.4   15.0  18.019452
26    101  296.4   36.3      100.9   23.8  23.496236
27    197  177.0    9.3        6.4   12.8  12.714552
28    109  255.4   26.9        5.5   19.8  19.770633
29    177  170.2    7.8       35.2   11.7  12.107055
30     57  136.2   19.2       16.6   13.2  12.682396
31    106   25.0   11.0       29.7    7.2   5.875633
32    160  172.5   18.1       30.7   14.4  14.182708
33     84  213.5   43.0       33.8   21.7  20.870414
34    124  229.5   32.3       74.2   19.7  19.580075
35     85  193.2   18.4       65.7   15.2  15.214834
36    126    7.8   38.9       50.6    6.6  10.393226
37    183  287.6   43.0       71.8   26.2  24.361711
38     80   76.4   26.7       22.3   11.8  11.296562
39    116  139.2   14.3       25.6   12.2  11.887758
40    129   59.6   12.0       43.1    9.7   7.696920
41    128  220.3   49.0        3.2   24.7  22.337391
42     60   53.5    2.0       21.4    8.1   5.499992
43    122  224.0    2.4       15.6   11.6  13.611477
44     27  240.1   16.7       22.9   15.9  17.101191
45     40  202.5   22.3       31.6   16.6  16.398619
46     45  175.1   22.5       31.5   14.9  15.145567
47    191   75.5   10.8        6.0    9.9   8.217756
48     31  112.9   17.4       38.6   11.9  11.240156
49    154  187.8   21.1        9.5   15.6  15.477110
50     32   97.2    1.5       30.0    9.6   7.463736
51     13   97.5    7.6        7.2    9.7   8.643342
52    117   76.4    0.8       14.8    9.4   6.350119
53     78    5.4   29.9        9.4    5.3   8.562030
54    131  265.2    2.9       43.0   12.7  15.648029
55     28  248.8   27.1       22.9   18.9  19.497462
56     18   69.2   20.5       18.3   11.3   9.773207
57    141  193.7   35.4       75.6   19.2  18.485001
58    134   36.9   38.6       65.6   10.8  11.707005
59     97  184.9   21.0       22.0   15.5  15.321104

In [54]:
dt.corr()

              index        TV     Radio  Newspaper     Sales  Predicted
index      1.000000  0.216008 -0.091564   0.001199  0.095705   0.128056
TV         0.216008  1.000000  0.128668   0.079286  0.812386   0.868771
Radio     -0.091564  0.128668  1.000000   0.364127  0.587212   0.602880
Newspaper  0.001199  0.079286  0.364127   1.000000  0.227696   0.245546
Sales      0.095705  0.812386  0.587212   0.227696  1.000000   0.946814
Predicted  0.128056  0.868771  0.602880   0.245546  0.946814   1.000000

## Stats model

In [55]:
train, test = train_test_split(df, train_size=0.7, random_state=5)

In [56]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [57]:
model_1 = smf.ols(formula='Sales ~ TV + Radio + Newspaper', data = train).fit()

In [58]:
print(model_1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.900
Model:                            OLS   Adj. R-squared:                  0.898
Method:                 Least Squares   F-statistic:                     407.0
Date:                Wed, 15 Jun 2022   Prob (F-statistic):           1.04e-67
Time:                        16:12:58   Log-Likelihood:                -273.79
No. Observations:                 140   AIC:                             555.6
Df Residuals:                     136   BIC:                             567.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.9788      0.370      8.046      0.000       2.247       3.711
TV             0.0467      0.002     27.224      0.000       0.043       0.050
Radio          0.1850      0.010     17.755      0.000       0.164       0.206
Newspaper     -0.0015      0.007     -0.223      0.824      -0.015       0.012
==============================================================================
Omnibus:                       56.097   Durbin-Watson:                   1.934
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              160.787
Skew:                          -1.575   Prob(JB):                     1.22e-35
Kurtosis:                       7.201   Cond. No.                         431.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [59]:
model_1.params #coeff.

Intercept    2.978767
TV           0.046685
Radio        0.185016
Newspaper   -0.001530
dtype: float64

In [60]:
model_1.pvalues

Intercept    3.757802e-13
TV           6.635435e-57
Radio        3.098625e-37
Newspaper    8.239084e-01
dtype: float64